// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: proto/asset_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetService_UpdateAsset_FullMethodName       = "/asset_service.AssetService/UpdateAsset"
	AssetService_UpdateIssue_FullMethodName       = "/asset_service.AssetService/UpdateIssue"
	AssetService_UpdateNote_FullMethodName        = "/asset_service.AssetService/UpdateNote"
	AssetService_UpdateAssetClass_FullMethodName  = "/asset_service.AssetService/UpdateAssetClass"
	AssetService_UpdateCriticality_FullMethodName = "/asset_service.AssetService/UpdateCriticality"
	AssetService_UpdateDeviceType_FullMethodName  = "/asset_service.AssetService/UpdateDeviceType"
)

// AssetServiceClient is the client API for AssetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The gRPC Service Definition
type AssetServiceClient interface {
	// Asset Operations
	UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*AssetResponse, error)
	// Issue Operations
	UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*IssueResponse, error)
	// Note Operations
	UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*NoteResponse, error)
	// Metadata Operations
	UpdateAssetClass(ctx context.Context, in *UpdateAssetClassRequest, opts ...grpc.CallOption) (*AssetClassResponse, error)
	UpdateCriticality(ctx context.Context, in *UpdateCriticalityRequest, opts ...grpc.CallOption) (*CriticalityResponse, error)
	UpdateDeviceType(ctx context.Context, in *UpdateDeviceTypeRequest, opts ...grpc.CallOption) (*DeviceTypeResponse, error)
}

type assetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetServiceClient(cc grpc.ClientConnInterface) AssetServiceClient {
	return &assetServiceClient{cc}
}

func (c *assetServiceClient) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*AssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateIssue(ctx context.Context, in *UpdateIssueRequest, opts ...grpc.CallOption) (*IssueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateNote(ctx context.Context, in *UpdateNoteRequest, opts ...grpc.CallOption) (*NoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NoteResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateAssetClass(ctx context.Context, in *UpdateAssetClassRequest, opts ...grpc.CallOption) (*AssetClassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetClassResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateAssetClass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateCriticality(ctx context.Context, in *UpdateCriticalityRequest, opts ...grpc.CallOption) (*CriticalityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CriticalityResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateCriticality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetServiceClient) UpdateDeviceType(ctx context.Context, in *UpdateDeviceTypeRequest, opts ...grpc.CallOption) (*DeviceTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceTypeResponse)
	err := c.cc.Invoke(ctx, AssetService_UpdateDeviceType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetServiceServer is the server API for AssetService service.
// All implementations must embed UnimplementedAssetServiceServer
// for forward compatibility.
//
// The gRPC Service Definition
type AssetServiceServer interface {
	// Asset Operations
	UpdateAsset(context.Context, *UpdateAssetRequest) (*AssetResponse, error)
	// Issue Operations
	UpdateIssue(context.Context, *UpdateIssueRequest) (*IssueResponse, error)
	// Note Operations
	UpdateNote(context.Context, *UpdateNoteRequest) (*NoteResponse, error)
	// Metadata Operations
	UpdateAssetClass(context.Context, *UpdateAssetClassRequest) (*AssetClassResponse, error)
	UpdateCriticality(context.Context, *UpdateCriticalityRequest) (*CriticalityResponse, error)
	UpdateDeviceType(context.Context, *UpdateDeviceTypeRequest) (*DeviceTypeResponse, error)
	mustEmbedUnimplementedAssetServiceServer()
}

// UnimplementedAssetServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetServiceServer struct{}

func (UnimplementedAssetServiceServer) UpdateAsset(context.Context, *UpdateAssetRequest) (*AssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAsset not implemented")
}
func (UnimplementedAssetServiceServer) UpdateIssue(context.Context, *UpdateIssueRequest) (*IssueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateIssue not implemented")
}
func (UnimplementedAssetServiceServer) UpdateNote(context.Context, *UpdateNoteRequest) (*NoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNote not implemented")
}
func (UnimplementedAssetServiceServer) UpdateAssetClass(context.Context, *UpdateAssetClassRequest) (*AssetClassResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAssetClass not implemented")
}
func (UnimplementedAssetServiceServer) UpdateCriticality(context.Context, *UpdateCriticalityRequest) (*CriticalityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCriticality not implemented")
}
func (UnimplementedAssetServiceServer) UpdateDeviceType(context.Context, *UpdateDeviceTypeRequest) (*DeviceTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDeviceType not implemented")
}
func (UnimplementedAssetServiceServer) mustEmbedUnimplementedAssetServiceServer() {}
func (UnimplementedAssetServiceServer) testEmbeddedByValue()                      {}

// UnsafeAssetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetServiceServer will
// result in compilation errors.
type UnsafeAssetServiceServer interface {
	mustEmbedUnimplementedAssetServiceServer()
}

func RegisterAssetServiceServer(s grpc.ServiceRegistrar, srv AssetServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetService_ServiceDesc, srv)
}

func _AssetService_UpdateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateAsset(ctx, req.(*UpdateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateIssue(ctx, req.(*UpdateIssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateNote(ctx, req.(*UpdateNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateAssetClass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetClassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateAssetClass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateAssetClass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateAssetClass(ctx, req.(*UpdateAssetClassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateCriticality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCriticalityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateCriticality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateCriticality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateCriticality(ctx, req.(*UpdateCriticalityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetService_UpdateDeviceType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDeviceTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetServiceServer).UpdateDeviceType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetService_UpdateDeviceType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetServiceServer).UpdateDeviceType(ctx, req.(*UpdateDeviceTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetService_ServiceDesc is the grpc.ServiceDesc for AssetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asset_service.AssetService",
	HandlerType: (*AssetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAsset",
			Handler:    _AssetService_UpdateAsset_Handler,
		},
		{
			MethodName: "UpdateIssue",
			Handler:    _AssetService_UpdateIssue_Handler,
		},
		{
			MethodName: "UpdateNote",
			Handler:    _AssetService_UpdateNote_Handler,
		},
		{
			MethodName: "UpdateAssetClass",
			Handler:    _AssetService_UpdateAssetClass_Handler,
		},
		{
			MethodName: "UpdateCriticality",
			Handler:    _AssetService_UpdateCriticality_Handler,
		},
		{
			MethodName: "UpdateDeviceType",
			Handler:    _AssetService_UpdateDeviceType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/asset_service.proto",
}
