// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/asset_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- ASSET MESSAGES ---
type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	AssetClassId  *int32                 `protobuf:"varint,3,opt,name=asset_class_id,json=assetClassId,proto3,oneof" json:"asset_class_id,omitempty"`
	CriticalityId *int32                 `protobuf:"varint,4,opt,name=criticality_id,json=criticalityId,proto3,oneof" json:"criticality_id,omitempty"`
	DeviceInfo    *DeviceDetail          `protobuf:"bytes,5,opt,name=device_info,json=deviceInfo,proto3,oneof" json:"device_info,omitempty"`
	NetworkInfo   *NetworkDetail         `protobuf:"bytes,6,opt,name=network_info,json=networkInfo,proto3,oneof" json:"network_info,omitempty"`
	SoftwareInfo  *SoftwareDetail        `protobuf:"bytes,7,opt,name=software_info,json=softwareInfo,proto3,oneof" json:"software_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateAssetRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAssetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAssetRequest) GetAssetClassId() int32 {
	if x != nil && x.AssetClassId != nil {
		return *x.AssetClassId
	}
	return 0
}

func (x *UpdateAssetRequest) GetCriticalityId() int32 {
	if x != nil && x.CriticalityId != nil {
		return *x.CriticalityId
	}
	return 0
}

func (x *UpdateAssetRequest) GetDeviceInfo() *DeviceDetail {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

func (x *UpdateAssetRequest) GetNetworkInfo() *NetworkDetail {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

func (x *UpdateAssetRequest) GetSoftwareInfo() *SoftwareDetail {
	if x != nil {
		return x.SoftwareInfo
	}
	return nil
}

type DeviceDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      *string                `protobuf:"bytes,1,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	DeviceTypeId  *int32                 `protobuf:"varint,2,opt,name=device_type_id,json=deviceTypeId,proto3,oneof" json:"device_type_id,omitempty"`
	IpAddress     *string                `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3,oneof" json:"ip_address,omitempty"`
	MacAddress    *string                `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3,oneof" json:"mac_address,omitempty"`
	OsName        *string                `protobuf:"bytes,5,opt,name=os_name,json=osName,proto3,oneof" json:"os_name,omitempty"`
	OsVersion     *string                `protobuf:"bytes,6,opt,name=os_version,json=osVersion,proto3,oneof" json:"os_version,omitempty"`
	HardwareCpe   *string                `protobuf:"bytes,7,opt,name=hardware_cpe,json=hardwareCpe,proto3,oneof" json:"hardware_cpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceDetail) Reset() {
	*x = DeviceDetail{}
	mi := &file_proto_asset_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceDetail) ProtoMessage() {}

func (x *DeviceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceDetail.ProtoReflect.Descriptor instead.
func (*DeviceDetail) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceDetail) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *DeviceDetail) GetDeviceTypeId() int32 {
	if x != nil && x.DeviceTypeId != nil {
		return *x.DeviceTypeId
	}
	return 0
}

func (x *DeviceDetail) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *DeviceDetail) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *DeviceDetail) GetOsName() string {
	if x != nil && x.OsName != nil {
		return *x.OsName
	}
	return ""
}

func (x *DeviceDetail) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

func (x *DeviceDetail) GetHardwareCpe() string {
	if x != nil && x.HardwareCpe != nil {
		return *x.HardwareCpe
	}
	return ""
}

type NetworkDetail struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManagementIp    *string                `protobuf:"bytes,1,opt,name=management_ip,json=managementIp,proto3,oneof" json:"management_ip,omitempty"`
	DeviceTypeId    *int32                 `protobuf:"varint,2,opt,name=device_type_id,json=deviceTypeId,proto3,oneof" json:"device_type_id,omitempty"`
	MacAddress      *string                `protobuf:"bytes,3,opt,name=mac_address,json=macAddress,proto3,oneof" json:"mac_address,omitempty"`
	FirmwareVersion *string                `protobuf:"bytes,4,opt,name=firmware_version,json=firmwareVersion,proto3,oneof" json:"firmware_version,omitempty"`
	ModelNumber     *string                `protobuf:"bytes,5,opt,name=model_number,json=modelNumber,proto3,oneof" json:"model_number,omitempty"`
	SerialNumber    *string                `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3,oneof" json:"serial_number,omitempty"`
	TotalPorts      *int32                 `protobuf:"varint,7,opt,name=total_ports,json=totalPorts,proto3,oneof" json:"total_ports,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkDetail) Reset() {
	*x = NetworkDetail{}
	mi := &file_proto_asset_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkDetail) ProtoMessage() {}

func (x *NetworkDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkDetail.ProtoReflect.Descriptor instead.
func (*NetworkDetail) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{2}
}

func (x *NetworkDetail) GetManagementIp() string {
	if x != nil && x.ManagementIp != nil {
		return *x.ManagementIp
	}
	return ""
}

func (x *NetworkDetail) GetDeviceTypeId() int32 {
	if x != nil && x.DeviceTypeId != nil {
		return *x.DeviceTypeId
	}
	return 0
}

func (x *NetworkDetail) GetMacAddress() string {
	if x != nil && x.MacAddress != nil {
		return *x.MacAddress
	}
	return ""
}

func (x *NetworkDetail) GetFirmwareVersion() string {
	if x != nil && x.FirmwareVersion != nil {
		return *x.FirmwareVersion
	}
	return ""
}

func (x *NetworkDetail) GetModelNumber() string {
	if x != nil && x.ModelNumber != nil {
		return *x.ModelNumber
	}
	return ""
}

func (x *NetworkDetail) GetSerialNumber() string {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return ""
}

func (x *NetworkDetail) GetTotalPorts() int32 {
	if x != nil && x.TotalPorts != nil {
		return *x.TotalPorts
	}
	return 0
}

type SoftwareDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name,proto3,oneof" json:"name,omitempty"`
	OsName        *string                `protobuf:"bytes,2,opt,name=os_name,json=osName,proto3,oneof" json:"os_name,omitempty"`
	OsVersion     *string                `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3,oneof" json:"os_version,omitempty"`
	Version       *string                `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Vendor        *string                `protobuf:"bytes,5,opt,name=vendor,proto3,oneof" json:"vendor,omitempty"`
	SoftwareCpe   *string                `protobuf:"bytes,6,opt,name=software_cpe,json=softwareCpe,proto3,oneof" json:"software_cpe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoftwareDetail) Reset() {
	*x = SoftwareDetail{}
	mi := &file_proto_asset_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoftwareDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoftwareDetail) ProtoMessage() {}

func (x *SoftwareDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoftwareDetail.ProtoReflect.Descriptor instead.
func (*SoftwareDetail) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{3}
}

func (x *SoftwareDetail) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SoftwareDetail) GetOsName() string {
	if x != nil && x.OsName != nil {
		return *x.OsName
	}
	return ""
}

func (x *SoftwareDetail) GetOsVersion() string {
	if x != nil && x.OsVersion != nil {
		return *x.OsVersion
	}
	return ""
}

func (x *SoftwareDetail) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *SoftwareDetail) GetVendor() string {
	if x != nil && x.Vendor != nil {
		return *x.Vendor
	}
	return ""
}

func (x *SoftwareDetail) GetSoftwareCpe() string {
	if x != nil && x.SoftwareCpe != nil {
		return *x.SoftwareCpe
	}
	return ""
}

type AssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AssetClassId  int32                  `protobuf:"varint,3,opt,name=asset_class_id,json=assetClassId,proto3" json:"asset_class_id,omitempty"`
	CriticalityId int32                  `protobuf:"varint,4,opt,name=criticality_id,json=criticalityId,proto3" json:"criticality_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetResponse) Reset() {
	*x = AssetResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetResponse) ProtoMessage() {}

func (x *AssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetResponse.ProtoReflect.Descriptor instead.
func (*AssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{4}
}

func (x *AssetResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetResponse) GetAssetClassId() int32 {
	if x != nil {
		return x.AssetClassId
	}
	return 0
}

func (x *AssetResponse) GetCriticalityId() int32 {
	if x != nil {
		return x.CriticalityId
	}
	return 0
}

func (x *AssetResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// --- ISSUE MESSAGES ---
type UpdateIssueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IssueTypeId     *int32                 `protobuf:"varint,2,opt,name=issue_type_id,json=issueTypeId,proto3,oneof" json:"issue_type_id,omitempty"`
	StatusId        *int32                 `protobuf:"varint,3,opt,name=status_id,json=statusId,proto3,oneof" json:"status_id,omitempty"`
	IssueSourceId   *int32                 `protobuf:"varint,4,opt,name=issue_source_id,json=issueSourceId,proto3,oneof" json:"issue_source_id,omitempty"`
	ExternalIssueId *string                `protobuf:"bytes,5,opt,name=external_issue_id,json=externalIssueId,proto3,oneof" json:"external_issue_id,omitempty"`
	Description     *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateIssueRequest) Reset() {
	*x = UpdateIssueRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIssueRequest) ProtoMessage() {}

func (x *UpdateIssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIssueRequest.ProtoReflect.Descriptor instead.
func (*UpdateIssueRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateIssueRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateIssueRequest) GetIssueTypeId() int32 {
	if x != nil && x.IssueTypeId != nil {
		return *x.IssueTypeId
	}
	return 0
}

func (x *UpdateIssueRequest) GetStatusId() int32 {
	if x != nil && x.StatusId != nil {
		return *x.StatusId
	}
	return 0
}

func (x *UpdateIssueRequest) GetIssueSourceId() int32 {
	if x != nil && x.IssueSourceId != nil {
		return *x.IssueSourceId
	}
	return 0
}

func (x *UpdateIssueRequest) GetExternalIssueId() string {
	if x != nil && x.ExternalIssueId != nil {
		return *x.ExternalIssueId
	}
	return ""
}

func (x *UpdateIssueRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type IssueResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetId         int32                  `protobuf:"varint,2,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	StatusId        int32                  `protobuf:"varint,3,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	ExternalIssueId string                 `protobuf:"bytes,4,opt,name=external_issue_id,json=externalIssueId,proto3" json:"external_issue_id,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssueResponse) Reset() {
	*x = IssueResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueResponse) ProtoMessage() {}

func (x *IssueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueResponse.ProtoReflect.Descriptor instead.
func (*IssueResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{6}
}

func (x *IssueResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IssueResponse) GetAssetId() int32 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *IssueResponse) GetStatusId() int32 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *IssueResponse) GetExternalIssueId() string {
	if x != nil {
		return x.ExternalIssueId
	}
	return ""
}

func (x *IssueResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// --- NOTE MESSAGES ---
type UpdateNoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetIssueId  *int32                 `protobuf:"varint,2,opt,name=asset_issue_id,json=assetIssueId,proto3,oneof" json:"asset_issue_id,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoteRequest) Reset() {
	*x = UpdateNoteRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoteRequest) ProtoMessage() {}

func (x *UpdateNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoteRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateNoteRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNoteRequest) GetAssetIssueId() int32 {
	if x != nil && x.AssetIssueId != nil {
		return *x.AssetIssueId
	}
	return 0
}

func (x *UpdateNoteRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

type NoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoteResponse) Reset() {
	*x = NoteResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoteResponse) ProtoMessage() {}

func (x *NoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoteResponse.ProtoReflect.Descriptor instead.
func (*NoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{8}
}

func (x *NoteResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NoteResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// --- METADATA MESSAGES ---
type UpdateAssetClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Definition    *string                `protobuf:"bytes,3,opt,name=definition,proto3,oneof" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetClassRequest) Reset() {
	*x = UpdateAssetClassRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetClassRequest) ProtoMessage() {}

func (x *UpdateAssetClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetClassRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetClassRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateAssetClassRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateAssetClassRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAssetClassRequest) GetDefinition() string {
	if x != nil && x.Definition != nil {
		return *x.Definition
	}
	return ""
}

type AssetClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetClassResponse) Reset() {
	*x = AssetClassResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetClassResponse) ProtoMessage() {}

func (x *AssetClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetClassResponse.ProtoReflect.Descriptor instead.
func (*AssetClassResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{10}
}

func (x *AssetClassResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AssetClassResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateCriticalityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Value         *int32                 `protobuf:"varint,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCriticalityRequest) Reset() {
	*x = UpdateCriticalityRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCriticalityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCriticalityRequest) ProtoMessage() {}

func (x *UpdateCriticalityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCriticalityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCriticalityRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateCriticalityRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCriticalityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCriticalityRequest) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type CriticalityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CriticalityResponse) Reset() {
	*x = CriticalityResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CriticalityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriticalityResponse) ProtoMessage() {}

func (x *CriticalityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriticalityResponse.ProtoReflect.Descriptor instead.
func (*CriticalityResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{12}
}

func (x *CriticalityResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CriticalityResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CriticalityResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type UpdateDeviceTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AssetClassId  *int32                 `protobuf:"varint,2,opt,name=asset_class_id,json=assetClassId,proto3,oneof" json:"asset_class_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDeviceTypeRequest) Reset() {
	*x = UpdateDeviceTypeRequest{}
	mi := &file_proto_asset_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDeviceTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDeviceTypeRequest) ProtoMessage() {}

func (x *UpdateDeviceTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDeviceTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateDeviceTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateDeviceTypeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDeviceTypeRequest) GetAssetClassId() int32 {
	if x != nil && x.AssetClassId != nil {
		return *x.AssetClassId
	}
	return 0
}

func (x *UpdateDeviceTypeRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type DeviceTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceTypeResponse) Reset() {
	*x = DeviceTypeResponse{}
	mi := &file_proto_asset_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceTypeResponse) ProtoMessage() {}

func (x *DeviceTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceTypeResponse.ProtoReflect.Descriptor instead.
func (*DeviceTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeviceTypeResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeviceTypeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_asset_service_proto protoreflect.FileDescriptor

const file_proto_asset_service_proto_rawDesc = "" +
	"\n" +
	"\x19proto/asset_service.proto\x12\rasset_service\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x03\n" +
	"\x12UpdateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12)\n" +
	"\x0easset_class_id\x18\x03 \x01(\x05H\x01R\fassetClassId\x88\x01\x01\x12*\n" +
	"\x0ecriticality_id\x18\x04 \x01(\x05H\x02R\rcriticalityId\x88\x01\x01\x12A\n" +
	"\vdevice_info\x18\x05 \x01(\v2\x1b.asset_service.DeviceDetailH\x03R\n" +
	"deviceInfo\x88\x01\x01\x12D\n" +
	"\fnetwork_info\x18\x06 \x01(\v2\x1c.asset_service.NetworkDetailH\x04R\vnetworkInfo\x88\x01\x01\x12G\n" +
	"\rsoftware_info\x18\a \x01(\v2\x1d.asset_service.SoftwareDetailH\x05R\fsoftwareInfo\x88\x01\x01B\a\n" +
	"\x05_nameB\x11\n" +
	"\x0f_asset_class_idB\x11\n" +
	"\x0f_criticality_idB\x0e\n" +
	"\f_device_infoB\x0f\n" +
	"\r_network_infoB\x10\n" +
	"\x0e_software_info\"\xf9\x02\n" +
	"\fDeviceDetail\x12\x1f\n" +
	"\bhostname\x18\x01 \x01(\tH\x00R\bhostname\x88\x01\x01\x12)\n" +
	"\x0edevice_type_id\x18\x02 \x01(\x05H\x01R\fdeviceTypeId\x88\x01\x01\x12\"\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tH\x02R\tipAddress\x88\x01\x01\x12$\n" +
	"\vmac_address\x18\x04 \x01(\tH\x03R\n" +
	"macAddress\x88\x01\x01\x12\x1c\n" +
	"\aos_name\x18\x05 \x01(\tH\x04R\x06osName\x88\x01\x01\x12\"\n" +
	"\n" +
	"os_version\x18\x06 \x01(\tH\x05R\tosVersion\x88\x01\x01\x12&\n" +
	"\fhardware_cpe\x18\a \x01(\tH\x06R\vhardwareCpe\x88\x01\x01B\v\n" +
	"\t_hostnameB\x11\n" +
	"\x0f_device_type_idB\r\n" +
	"\v_ip_addressB\x0e\n" +
	"\f_mac_addressB\n" +
	"\n" +
	"\b_os_nameB\r\n" +
	"\v_os_versionB\x0f\n" +
	"\r_hardware_cpe\"\xaf\x03\n" +
	"\rNetworkDetail\x12(\n" +
	"\rmanagement_ip\x18\x01 \x01(\tH\x00R\fmanagementIp\x88\x01\x01\x12)\n" +
	"\x0edevice_type_id\x18\x02 \x01(\x05H\x01R\fdeviceTypeId\x88\x01\x01\x12$\n" +
	"\vmac_address\x18\x03 \x01(\tH\x02R\n" +
	"macAddress\x88\x01\x01\x12.\n" +
	"\x10firmware_version\x18\x04 \x01(\tH\x03R\x0ffirmwareVersion\x88\x01\x01\x12&\n" +
	"\fmodel_number\x18\x05 \x01(\tH\x04R\vmodelNumber\x88\x01\x01\x12(\n" +
	"\rserial_number\x18\x06 \x01(\tH\x05R\fserialNumber\x88\x01\x01\x12$\n" +
	"\vtotal_ports\x18\a \x01(\x05H\x06R\n" +
	"totalPorts\x88\x01\x01B\x10\n" +
	"\x0e_management_ipB\x11\n" +
	"\x0f_device_type_idB\x0e\n" +
	"\f_mac_addressB\x13\n" +
	"\x11_firmware_versionB\x0f\n" +
	"\r_model_numberB\x10\n" +
	"\x0e_serial_numberB\x0e\n" +
	"\f_total_ports\"\x9b\x02\n" +
	"\x0eSoftwareDetail\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1c\n" +
	"\aos_name\x18\x02 \x01(\tH\x01R\x06osName\x88\x01\x01\x12\"\n" +
	"\n" +
	"os_version\x18\x03 \x01(\tH\x02R\tosVersion\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x04 \x01(\tH\x03R\aversion\x88\x01\x01\x12\x1b\n" +
	"\x06vendor\x18\x05 \x01(\tH\x04R\x06vendor\x88\x01\x01\x12&\n" +
	"\fsoftware_cpe\x18\x06 \x01(\tH\x05R\vsoftwareCpe\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_os_nameB\r\n" +
	"\v_os_versionB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_vendorB\x0f\n" +
	"\r_software_cpe\"\xbb\x01\n" +
	"\rAssetResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x0easset_class_id\x18\x03 \x01(\x05R\fassetClassId\x12%\n" +
	"\x0ecriticality_id\x18\x04 \x01(\x05R\rcriticalityId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xce\x02\n" +
	"\x12UpdateIssueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12'\n" +
	"\rissue_type_id\x18\x02 \x01(\x05H\x00R\vissueTypeId\x88\x01\x01\x12 \n" +
	"\tstatus_id\x18\x03 \x01(\x05H\x01R\bstatusId\x88\x01\x01\x12+\n" +
	"\x0fissue_source_id\x18\x04 \x01(\x05H\x02R\rissueSourceId\x88\x01\x01\x12/\n" +
	"\x11external_issue_id\x18\x05 \x01(\tH\x03R\x0fexternalIssueId\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x04R\vdescription\x88\x01\x01B\x10\n" +
	"\x0e_issue_type_idB\f\n" +
	"\n" +
	"_status_idB\x12\n" +
	"\x10_issue_source_idB\x14\n" +
	"\x12_external_issue_idB\x0e\n" +
	"\f_description\"\xbe\x01\n" +
	"\rIssueResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\basset_id\x18\x02 \x01(\x05R\aassetId\x12\x1b\n" +
	"\tstatus_id\x18\x03 \x01(\x05R\bstatusId\x12*\n" +
	"\x11external_issue_id\x18\x04 \x01(\tR\x0fexternalIssueId\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8c\x01\n" +
	"\x11UpdateNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12)\n" +
	"\x0easset_issue_id\x18\x02 \x01(\x05H\x00R\fassetIssueId\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01B\x11\n" +
	"\x0f_asset_issue_idB\n" +
	"\n" +
	"\b_content\"8\n" +
	"\fNoteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\x7f\n" +
	"\x17UpdateAssetClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12#\n" +
	"\n" +
	"definition\x18\x03 \x01(\tH\x01R\n" +
	"definition\x88\x01\x01B\a\n" +
	"\x05_nameB\r\n" +
	"\v_definition\"8\n" +
	"\x12AssetClassResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"q\n" +
	"\x18UpdateCriticalityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05value\x18\x03 \x01(\x05H\x01R\x05value\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_value\"O\n" +
	"\x13CriticalityResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"\x89\x01\n" +
	"\x17UpdateDeviceTypeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12)\n" +
	"\x0easset_class_id\x18\x02 \x01(\x05H\x00R\fassetClassId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01B\x11\n" +
	"\x0f_asset_class_idB\a\n" +
	"\x05_name\"8\n" +
	"\x12DeviceTypeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\x9b\x04\n" +
	"\fAssetService\x12N\n" +
	"\vUpdateAsset\x12!.asset_service.UpdateAssetRequest\x1a\x1c.asset_service.AssetResponse\x12N\n" +
	"\vUpdateIssue\x12!.asset_service.UpdateIssueRequest\x1a\x1c.asset_service.IssueResponse\x12K\n" +
	"\n" +
	"UpdateNote\x12 .asset_service.UpdateNoteRequest\x1a\x1b.asset_service.NoteResponse\x12]\n" +
	"\x10UpdateAssetClass\x12&.asset_service.UpdateAssetClassRequest\x1a!.asset_service.AssetClassResponse\x12`\n" +
	"\x11UpdateCriticality\x12'.asset_service.UpdateCriticalityRequest\x1a\".asset_service.CriticalityResponse\x12]\n" +
	"\x10UpdateDeviceType\x12&.asset_service.UpdateDeviceTypeRequest\x1a!.asset_service.DeviceTypeResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_asset_service_proto_rawDescOnce sync.Once
	file_proto_asset_service_proto_rawDescData []byte
)

func file_proto_asset_service_proto_rawDescGZIP() []byte {
	file_proto_asset_service_proto_rawDescOnce.Do(func() {
		file_proto_asset_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_service_proto_rawDesc), len(file_proto_asset_service_proto_rawDesc)))
	})
	return file_proto_asset_service_proto_rawDescData
}

var file_proto_asset_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_asset_service_proto_goTypes = []any{
	(*UpdateAssetRequest)(nil),       // 0: asset_service.UpdateAssetRequest
	(*DeviceDetail)(nil),             // 1: asset_service.DeviceDetail
	(*NetworkDetail)(nil),            // 2: asset_service.NetworkDetail
	(*SoftwareDetail)(nil),           // 3: asset_service.SoftwareDetail
	(*AssetResponse)(nil),            // 4: asset_service.AssetResponse
	(*UpdateIssueRequest)(nil),       // 5: asset_service.UpdateIssueRequest
	(*IssueResponse)(nil),            // 6: asset_service.IssueResponse
	(*UpdateNoteRequest)(nil),        // 7: asset_service.UpdateNoteRequest
	(*NoteResponse)(nil),             // 8: asset_service.NoteResponse
	(*UpdateAssetClassRequest)(nil),  // 9: asset_service.UpdateAssetClassRequest
	(*AssetClassResponse)(nil),       // 10: asset_service.AssetClassResponse
	(*UpdateCriticalityRequest)(nil), // 11: asset_service.UpdateCriticalityRequest
	(*CriticalityResponse)(nil),      // 12: asset_service.CriticalityResponse
	(*UpdateDeviceTypeRequest)(nil),  // 13: asset_service.UpdateDeviceTypeRequest
	(*DeviceTypeResponse)(nil),       // 14: asset_service.DeviceTypeResponse
	(*timestamppb.Timestamp)(nil),    // 15: google.protobuf.Timestamp
}
var file_proto_asset_service_proto_depIdxs = []int32{
	1,  // 0: asset_service.UpdateAssetRequest.device_info:type_name -> asset_service.DeviceDetail
	2,  // 1: asset_service.UpdateAssetRequest.network_info:type_name -> asset_service.NetworkDetail
	3,  // 2: asset_service.UpdateAssetRequest.software_info:type_name -> asset_service.SoftwareDetail
	15, // 3: asset_service.AssetResponse.created_at:type_name -> google.protobuf.Timestamp
	15, // 4: asset_service.IssueResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: asset_service.AssetService.UpdateAsset:input_type -> asset_service.UpdateAssetRequest
	5,  // 6: asset_service.AssetService.UpdateIssue:input_type -> asset_service.UpdateIssueRequest
	7,  // 7: asset_service.AssetService.UpdateNote:input_type -> asset_service.UpdateNoteRequest
	9,  // 8: asset_service.AssetService.UpdateAssetClass:input_type -> asset_service.UpdateAssetClassRequest
	11, // 9: asset_service.AssetService.UpdateCriticality:input_type -> asset_service.UpdateCriticalityRequest
	13, // 10: asset_service.AssetService.UpdateDeviceType:input_type -> asset_service.UpdateDeviceTypeRequest
	4,  // 11: asset_service.AssetService.UpdateAsset:output_type -> asset_service.AssetResponse
	6,  // 12: asset_service.AssetService.UpdateIssue:output_type -> asset_service.IssueResponse
	8,  // 13: asset_service.AssetService.UpdateNote:output_type -> asset_service.NoteResponse
	10, // 14: asset_service.AssetService.UpdateAssetClass:output_type -> asset_service.AssetClassResponse
	12, // 15: asset_service.AssetService.UpdateCriticality:output_type -> asset_service.CriticalityResponse
	14, // 16: asset_service.AssetService.UpdateDeviceType:output_type -> asset_service.DeviceTypeResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_asset_service_proto_init() }
func file_proto_asset_service_proto_init() {
	if File_proto_asset_service_proto != nil {
		return
	}
	file_proto_asset_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_asset_service_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_service_proto_rawDesc), len(file_proto_asset_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_service_proto_goTypes,
		DependencyIndexes: file_proto_asset_service_proto_depIdxs,
		MessageInfos:      file_proto_asset_service_proto_msgTypes,
	}.Build()
	File_proto_asset_service_proto = out.File
	file_proto_asset_service_proto_goTypes = nil
	file_proto_asset_service_proto_depIdxs = nil
}
