// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAssetClass = `-- name: CreateAssetClass :one

INSERT INTO cis_asset_class (name, definition)
VALUES ($1, $2)
RETURNING id, name, definition
`

type CreateAssetClassParams struct {
	Name       string
	Definition pgtype.Text
}

// --- CIS ASSET CLASS ---
func (q *Queries) CreateAssetClass(ctx context.Context, arg CreateAssetClassParams) (CisAssetClass, error) {
	row := q.db.QueryRow(ctx, createAssetClass, arg.Name, arg.Definition)
	var i CisAssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Definition)
	return i, err
}

const createAssetCriticality = `-- name: CreateAssetCriticality :one

INSERT INTO cis_asset_criticality (name, value)
VALUES ($1, $2)
RETURNING id, name, value
`

type CreateAssetCriticalityParams struct {
	Name  string
	Value int32
}

// --- CIS ASSET CRITICALITY ---
func (q *Queries) CreateAssetCriticality(ctx context.Context, arg CreateAssetCriticalityParams) (CisAssetCriticality, error) {
	row := q.db.QueryRow(ctx, createAssetCriticality, arg.Name, arg.Value)
	var i CisAssetCriticality
	err := row.Scan(&i.ID, &i.Name, &i.Value)
	return i, err
}

const createAssetSource = `-- name: CreateAssetSource :one

INSERT INTO asset_source (name)
VALUES ($1)
RETURNING id, name
`

// --- ASSET SOURCE ---
func (q *Queries) CreateAssetSource(ctx context.Context, name string) (AssetSource, error) {
	row := q.db.QueryRow(ctx, createAssetSource, name)
	var i AssetSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createDeviceType = `-- name: CreateDeviceType :one

INSERT INTO device_type (asset_class_id, name)
VALUES ($1, $2)
RETURNING id, asset_class_id, name
`

type CreateDeviceTypeParams struct {
	AssetClassID int32
	Name         string
}

// --- DEVICE TYPE ---
func (q *Queries) CreateDeviceType(ctx context.Context, arg CreateDeviceTypeParams) (DeviceType, error) {
	row := q.db.QueryRow(ctx, createDeviceType, arg.AssetClassID, arg.Name)
	var i DeviceType
	err := row.Scan(&i.ID, &i.AssetClassID, &i.Name)
	return i, err
}

const createIssueCategory = `-- name: CreateIssueCategory :one

INSERT INTO cis_issue_category (name, description)
VALUES ($1, $2)
RETURNING id, name, description
`

type CreateIssueCategoryParams struct {
	Name        string
	Description pgtype.Text
}

// --- ISSUE CATEGORY ---
func (q *Queries) CreateIssueCategory(ctx context.Context, arg CreateIssueCategoryParams) (CisIssueCategory, error) {
	row := q.db.QueryRow(ctx, createIssueCategory, arg.Name, arg.Description)
	var i CisIssueCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const createIssueSource = `-- name: CreateIssueSource :one

INSERT INTO issue_source (name)
VALUES ($1)
RETURNING id, name
`

// --- ISSUE SOURCE ---
func (q *Queries) CreateIssueSource(ctx context.Context, name string) (IssueSource, error) {
	row := q.db.QueryRow(ctx, createIssueSource, name)
	var i IssueSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createIssueStatus = `-- name: CreateIssueStatus :one

INSERT INTO cis_issue_status (name)
VALUES ($1)
RETURNING id, name
`

// --- ISSUE STATUS ---
func (q *Queries) CreateIssueStatus(ctx context.Context, name string) (CisIssueStatus, error) {
	row := q.db.QueryRow(ctx, createIssueStatus, name)
	var i CisIssueStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createIssueType = `-- name: CreateIssueType :one

INSERT INTO issue_type (category_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, category_id, name, description
`

type CreateIssueTypeParams struct {
	CategoryID  int32
	Name        string
	Description pgtype.Text
}

// --- ISSUE TYPE ---
func (q *Queries) CreateIssueType(ctx context.Context, arg CreateIssueTypeParams) (IssueType, error) {
	row := q.db.QueryRow(ctx, createIssueType, arg.CategoryID, arg.Name, arg.Description)
	var i IssueType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const deleteAssetClass = `-- name: DeleteAssetClass :exec
DELETE FROM cis_asset_class
WHERE id = $1
`

func (q *Queries) DeleteAssetClass(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAssetClass, id)
	return err
}

const deleteAssetCriticality = `-- name: DeleteAssetCriticality :exec
DELETE FROM cis_asset_criticality
WHERE id = $1
`

func (q *Queries) DeleteAssetCriticality(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAssetCriticality, id)
	return err
}

const deleteAssetSource = `-- name: DeleteAssetSource :exec
DELETE FROM asset_source
WHERE id = $1
`

func (q *Queries) DeleteAssetSource(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAssetSource, id)
	return err
}

const deleteDeviceType = `-- name: DeleteDeviceType :exec
DELETE FROM device_type
WHERE id = $1
`

func (q *Queries) DeleteDeviceType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDeviceType, id)
	return err
}

const deleteIssueCategory = `-- name: DeleteIssueCategory :exec
DELETE FROM cis_issue_category
WHERE id = $1
`

func (q *Queries) DeleteIssueCategory(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIssueCategory, id)
	return err
}

const deleteIssueSource = `-- name: DeleteIssueSource :exec
DELETE FROM issue_source
WHERE id = $1
`

func (q *Queries) DeleteIssueSource(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIssueSource, id)
	return err
}

const deleteIssueStatus = `-- name: DeleteIssueStatus :exec
DELETE FROM cis_issue_status
WHERE id = $1
`

func (q *Queries) DeleteIssueStatus(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIssueStatus, id)
	return err
}

const deleteIssueType = `-- name: DeleteIssueType :exec
DELETE FROM issue_type
WHERE id = $1
`

func (q *Queries) DeleteIssueType(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIssueType, id)
	return err
}

const getAssetClassByID = `-- name: GetAssetClassByID :one
SELECT id, name, definition FROM cis_asset_class
WHERE id = $1
`

func (q *Queries) GetAssetClassByID(ctx context.Context, id int32) (CisAssetClass, error) {
	row := q.db.QueryRow(ctx, getAssetClassByID, id)
	var i CisAssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Definition)
	return i, err
}

const getAssetCriticalityByID = `-- name: GetAssetCriticalityByID :one
SELECT id, name, value FROM cis_asset_criticality
WHERE id = $1
`

func (q *Queries) GetAssetCriticalityByID(ctx context.Context, id int32) (CisAssetCriticality, error) {
	row := q.db.QueryRow(ctx, getAssetCriticalityByID, id)
	var i CisAssetCriticality
	err := row.Scan(&i.ID, &i.Name, &i.Value)
	return i, err
}

const getAssetSourceByID = `-- name: GetAssetSourceByID :one
SELECT id, name FROM asset_source
WHERE id = $1
`

func (q *Queries) GetAssetSourceByID(ctx context.Context, id int32) (AssetSource, error) {
	row := q.db.QueryRow(ctx, getAssetSourceByID, id)
	var i AssetSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getDeviceTypeByID = `-- name: GetDeviceTypeByID :one
SELECT id, asset_class_id, name FROM device_type
WHERE id = $1
`

func (q *Queries) GetDeviceTypeByID(ctx context.Context, id int32) (DeviceType, error) {
	row := q.db.QueryRow(ctx, getDeviceTypeByID, id)
	var i DeviceType
	err := row.Scan(&i.ID, &i.AssetClassID, &i.Name)
	return i, err
}

const getIssueCategoryByID = `-- name: GetIssueCategoryByID :one
SELECT id, name, description FROM cis_issue_category
WHERE id = $1
`

func (q *Queries) GetIssueCategoryByID(ctx context.Context, id int32) (CisIssueCategory, error) {
	row := q.db.QueryRow(ctx, getIssueCategoryByID, id)
	var i CisIssueCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const getIssueSourceByID = `-- name: GetIssueSourceByID :one
SELECT id, name FROM issue_source
WHERE id = $1
`

func (q *Queries) GetIssueSourceByID(ctx context.Context, id int32) (IssueSource, error) {
	row := q.db.QueryRow(ctx, getIssueSourceByID, id)
	var i IssueSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getIssueStatusByID = `-- name: GetIssueStatusByID :one
SELECT id, name FROM cis_issue_status
WHERE id = $1
`

func (q *Queries) GetIssueStatusByID(ctx context.Context, id int32) (CisIssueStatus, error) {
	row := q.db.QueryRow(ctx, getIssueStatusByID, id)
	var i CisIssueStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getIssueTypeByID = `-- name: GetIssueTypeByID :one
SELECT id, category_id, name, description FROM issue_type
WHERE id = $1
`

func (q *Queries) GetIssueTypeByID(ctx context.Context, id int32) (IssueType, error) {
	row := q.db.QueryRow(ctx, getIssueTypeByID, id)
	var i IssueType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const listAssetClasses = `-- name: ListAssetClasses :many
SELECT id, name, definition FROM cis_asset_class
ORDER BY name
`

func (q *Queries) ListAssetClasses(ctx context.Context) ([]CisAssetClass, error) {
	rows, err := q.db.Query(ctx, listAssetClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CisAssetClass
	for rows.Next() {
		var i CisAssetClass
		if err := rows.Scan(&i.ID, &i.Name, &i.Definition); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetCriticalities = `-- name: ListAssetCriticalities :many
SELECT id, name, value FROM cis_asset_criticality
ORDER BY value DESC
`

func (q *Queries) ListAssetCriticalities(ctx context.Context) ([]CisAssetCriticality, error) {
	rows, err := q.db.Query(ctx, listAssetCriticalities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CisAssetCriticality
	for rows.Next() {
		var i CisAssetCriticality
		if err := rows.Scan(&i.ID, &i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetSources = `-- name: ListAssetSources :many
SELECT id, name FROM asset_source
ORDER BY name
`

func (q *Queries) ListAssetSources(ctx context.Context) ([]AssetSource, error) {
	rows, err := q.db.Query(ctx, listAssetSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSource
	for rows.Next() {
		var i AssetSource
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeviceTypesByClass = `-- name: ListDeviceTypesByClass :many
SELECT id, asset_class_id, name FROM device_type
WHERE asset_class_id = $1
ORDER BY name
`

func (q *Queries) ListDeviceTypesByClass(ctx context.Context, assetClassID int32) ([]DeviceType, error) {
	rows, err := q.db.Query(ctx, listDeviceTypesByClass, assetClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceType
	for rows.Next() {
		var i DeviceType
		if err := rows.Scan(&i.ID, &i.AssetClassID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueCategories = `-- name: ListIssueCategories :many
SELECT id, name, description FROM cis_issue_category
ORDER BY name
`

func (q *Queries) ListIssueCategories(ctx context.Context) ([]CisIssueCategory, error) {
	rows, err := q.db.Query(ctx, listIssueCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CisIssueCategory
	for rows.Next() {
		var i CisIssueCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueSources = `-- name: ListIssueSources :many
SELECT id, name FROM issue_source
ORDER BY name
`

func (q *Queries) ListIssueSources(ctx context.Context) ([]IssueSource, error) {
	rows, err := q.db.Query(ctx, listIssueSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueSource
	for rows.Next() {
		var i IssueSource
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueStatuses = `-- name: ListIssueStatuses :many
SELECT id, name FROM cis_issue_status
ORDER BY id
`

func (q *Queries) ListIssueStatuses(ctx context.Context) ([]CisIssueStatus, error) {
	rows, err := q.db.Query(ctx, listIssueStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CisIssueStatus
	for rows.Next() {
		var i CisIssueStatus
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueTypesByCategory = `-- name: ListIssueTypesByCategory :many
SELECT id, category_id, name, description FROM issue_type
WHERE category_id = $1
ORDER BY name
`

func (q *Queries) ListIssueTypesByCategory(ctx context.Context, categoryID int32) ([]IssueType, error) {
	rows, err := q.db.Query(ctx, listIssueTypesByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueType
	for rows.Next() {
		var i IssueType
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssetClass = `-- name: UpdateAssetClass :one
UPDATE cis_asset_class
SET name = $2, definition = $3
WHERE id = $1
RETURNING id, name, definition
`

type UpdateAssetClassParams struct {
	ID         int32
	Name       string
	Definition pgtype.Text
}

func (q *Queries) UpdateAssetClass(ctx context.Context, arg UpdateAssetClassParams) (CisAssetClass, error) {
	row := q.db.QueryRow(ctx, updateAssetClass, arg.ID, arg.Name, arg.Definition)
	var i CisAssetClass
	err := row.Scan(&i.ID, &i.Name, &i.Definition)
	return i, err
}

const updateAssetCriticality = `-- name: UpdateAssetCriticality :one
UPDATE cis_asset_criticality
SET name = $2, value = $3
WHERE id = $1
RETURNING id, name, value
`

type UpdateAssetCriticalityParams struct {
	ID    int32
	Name  string
	Value int32
}

func (q *Queries) UpdateAssetCriticality(ctx context.Context, arg UpdateAssetCriticalityParams) (CisAssetCriticality, error) {
	row := q.db.QueryRow(ctx, updateAssetCriticality, arg.ID, arg.Name, arg.Value)
	var i CisAssetCriticality
	err := row.Scan(&i.ID, &i.Name, &i.Value)
	return i, err
}

const updateAssetSource = `-- name: UpdateAssetSource :one
UPDATE asset_source
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateAssetSourceParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateAssetSource(ctx context.Context, arg UpdateAssetSourceParams) (AssetSource, error) {
	row := q.db.QueryRow(ctx, updateAssetSource, arg.ID, arg.Name)
	var i AssetSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateDeviceType = `-- name: UpdateDeviceType :one
UPDATE device_type
SET asset_class_id = $2, name = $3
WHERE id = $1
RETURNING id, asset_class_id, name
`

type UpdateDeviceTypeParams struct {
	ID           int32
	AssetClassID int32
	Name         string
}

func (q *Queries) UpdateDeviceType(ctx context.Context, arg UpdateDeviceTypeParams) (DeviceType, error) {
	row := q.db.QueryRow(ctx, updateDeviceType, arg.ID, arg.AssetClassID, arg.Name)
	var i DeviceType
	err := row.Scan(&i.ID, &i.AssetClassID, &i.Name)
	return i, err
}

const updateIssueCategory = `-- name: UpdateIssueCategory :one
UPDATE cis_issue_category
SET name = $2, description = $3
WHERE id = $1
RETURNING id, name, description
`

type UpdateIssueCategoryParams struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateIssueCategory(ctx context.Context, arg UpdateIssueCategoryParams) (CisIssueCategory, error) {
	row := q.db.QueryRow(ctx, updateIssueCategory, arg.ID, arg.Name, arg.Description)
	var i CisIssueCategory
	err := row.Scan(&i.ID, &i.Name, &i.Description)
	return i, err
}

const updateIssueSource = `-- name: UpdateIssueSource :one
UPDATE issue_source
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateIssueSourceParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateIssueSource(ctx context.Context, arg UpdateIssueSourceParams) (IssueSource, error) {
	row := q.db.QueryRow(ctx, updateIssueSource, arg.ID, arg.Name)
	var i IssueSource
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE cis_issue_status
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateIssueStatusParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (CisIssueStatus, error) {
	row := q.db.QueryRow(ctx, updateIssueStatus, arg.ID, arg.Name)
	var i CisIssueStatus
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateIssueType = `-- name: UpdateIssueType :one
UPDATE issue_type
SET category_id = $2, name = $3, description = $4
WHERE id = $1
RETURNING id, category_id, name, description
`

type UpdateIssueTypeParams struct {
	ID          int32
	CategoryID  int32
	Name        string
	Description pgtype.Text
}

func (q *Queries) UpdateIssueType(ctx context.Context, arg UpdateIssueTypeParams) (IssueType, error) {
	row := q.db.QueryRow(ctx, updateIssueType,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
	)
	var i IssueType
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
	)
	return i, err
}
