// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID            int32
	Name          string
	AssetClassID  int32
	CriticalityID int32
	CreatedAt     pgtype.Timestamptz
}

type AssetIssue struct {
	ID              int32
	AssetID         int32
	IssueTypeID     int32
	StatusID        int32
	IssueSourceID   int32
	ExternalIssueID string
	Description     pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type AssetNote struct {
	ID           int32
	AssetID      int32
	AssetIssueID pgtype.Int4
	AuthorUserID int32
	Content      string
	CreatedAt    pgtype.Timestamptz
}

type AssetSource struct {
	ID   int32
	Name string
}

type AssetSourceMap struct {
	AssetID       int32
	AssetSourceID int32
}

type CisAssetClass struct {
	ID         int32
	Name       string
	Definition pgtype.Text
}

type CisAssetCriticality struct {
	ID    int32
	Name  string
	Value int32
}

type CisIssueCategory struct {
	ID          int32
	Name        string
	Description pgtype.Text
}

type CisIssueStatus struct {
	ID   int32
	Name string
}

type DeviceDetail struct {
	AssetID      int32
	Hostname     string
	DeviceTypeID int32
	IpAddress    pgtype.Text
	MacAddress   pgtype.Text
	OsName       pgtype.Text
	OsVersion    pgtype.Text
	HardwareCpe  pgtype.Text
	LastSeen     pgtype.Timestamptz
}

type DeviceType struct {
	ID           int32
	AssetClassID int32
	Name         string
}

type IssueSource struct {
	ID   int32
	Name string
}

type IssueType struct {
	ID          int32
	CategoryID  int32
	Name        string
	Description pgtype.Text
}

type NetworkDetail struct {
	AssetID         int32
	ManagementIp    pgtype.Text
	DeviceTypeID    int32
	MacAddress      pgtype.Text
	FirmwareVersion pgtype.Text
	ModelNumber     pgtype.Text
	SerialNumber    pgtype.Text
	TotalPorts      pgtype.Int4
	LastSeen        pgtype.Timestamptz
}

type SoftwareDetail struct {
	AssetID     int32
	Name        string
	OsName      pgtype.Text
	OsVersion   pgtype.Text
	Version     pgtype.Text
	Vendor      pgtype.Text
	SoftwareCpe pgtype.Text
	LastSeen    pgtype.Timestamptz
}
